# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 20:04
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_flexslider_slide', serialize=False, to='cms.CMSPlugin')),
                ('caption', ckeditor.fields.RichTextField(blank=True, verbose_name='caption')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='slide image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_flexslider_slider', serialize=False, to='cms.CMSPlugin')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('%', '%'), ('px', 'px'), ('em', 'em'), ('rem', 'rem')], default='%', max_length=3)),
                ('animation', models.CharField(choices=[('fade', 'fade'), ('slide', 'slide')], default='fade', max_length=5)),
                ('slideshow_speed', models.PositiveSmallIntegerField(default=7000, verbose_name='slide show speed in ms')),
                ('animation_speed', models.PositiveSmallIntegerField(default=600, verbose_name='animation speed in ms')),
                ('randomize', models.BooleanField(default=False)),
                ('control_nav', models.BooleanField(default=True)),
                ('pause_on_action', models.BooleanField(default=False)),
                ('pause_on_hover', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
